src/books/urls.py
from django.urls import path
from . import views


app_name = 'books'

urlpatterns = [
    path('main/', views.BookListMainPageView.as_view(), name='main'),

    path('', views.BookListView.as_view(), name='books'),
    path('book-create/', views.BookCreateView.as_view(), name='create'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book'),
    path('book-upd/<int:pk>', views.BookUpdateView.as_view(), name='update'),
    path('book-del/<int:pk>', views.BookDelView.as_view(), name='del'),
    path('import-CSV', views.ImportCSVView.as_view(), name='import_CSV'),

    path('manager-list/', views.BookManagerListView.as_view(), name='books_manager'),
    
]

src/carts/urls.py
from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('delete-book/<int:pk>', views.BookInCartDeleteView.as_view(), name='del_book'),
    path('update-cart', views.UpdateCartView.as_view(), name='upd_cart'),
]

src/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.CreateOrderView.as_view(), name='create'),
    path('list/', views.OrderListView.as_view(), name='list'),
    path('manager-list/', views.OrderManagerListView.as_view(), name='m_list'),
    path('update/<int:pk>', views.OrderManagerUpdateView.as_view(), name='update'),
    path('cancel/<int:pk>', views.CancelOrderView.as_view(), name='cancel'),
    path('comment/<int:pk>', views.CommentOrderView.as_view(), name='comment'),
] 

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from proj import settings

from django.http import HttpResponseRedirect
from django.urls import reverse



def redirect_to_books(request):
    return HttpResponseRedirect(reverse('books:books'))


urlpatterns = [
    path('admin/', admin.site.urls),
    path('directories/', include('directories.urls', namespace='dirs')),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('search/', include('search.urls', namespace='search')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('', redirect_to_books, name='main'),

] 


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

src/users/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name = 'users'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile'),
    path('update-profile/<int:pk>', views.UpdateProfileView.as_view(), name='update'),


]    
    

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
    <title> {% block title %}Here will be Title{% endblock title %}</title>
</head>

<body class="container-xl">
    
    {% include './header.html' %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            {% if message.level == 30 %}
                <div class="alert alert-danger" role="alert">
            {% else %}
                <div class="alert alert-success" role="alert">    
            {% endif %}
                    {{ message }}
                </div>

        {% endfor %}
    </ul>
    {% endif %}

    {% block body %}Here will be Body{% endblock body %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
 
</html>

src/templates/book_card.html
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 g-4">
    <div class="card " >
        <div class="wrap">
            <a href="{% url 'books:book' book.pk %}">
            <img src="{{ book.picture.url }}" class="card-img-top rounded pict "  alt="">
            </a>    
        </div>
        <ul class="list-group list-group-flush">
            <h5><a class="list-group-item text-decoration-none text-reset txt-overflow " href="{% url 'books:book' book.pk %}">{{ book.name }}</a></h5>
            <li class="list-group-item txt-overflow"><span class="fs-6">Автор(ы):</span>                                    
                {% for author in book.authors.all %}
                    <a class="text-decoration-none text-reset  fs-6 link-hover" href="{% url 'dirs:author' author.pk %}"> {{author.name}} </a>
                {% endfor %}
                <br>

                
                Рейтинг: {{ book.rating }}
                <br>
                <a class="w-100 btn btn-success " href="{% url 'carts:cart' %}?book_id={{ book.pk }}">В корзину</a>
            </li>
        </ul>
        <div class="price-label">
            {{book.price|floatformat:2}} BYN
        </div>
    </div>        
</div>

src/templates/directories_item.html
{% load book_filter_tags %}

<div class="col-xs-12 col-sm-6 col-md-3 col-lg-2">
    <div class="card " >
        {% if item.picture %}
            <div class="dir_wrap">
                <a href="{% url url_det item.pk %}">
                    <img src="{{ item.picture.url }}" class="card-img-top rounded pict  "  alt="picture">
                </a>    
            </div>
        {% endif %}

        <ul class="list-group list-group-flush">
            <li class="list-group-item"><h4 class="name txt-overflow"><a class="text-decoration-none text-reset " href="{% url url_det item.pk %}">{{ item.name }}</a></h4></li>
            {% if request.user|has_group:'manager' %}
                <li class="list-group-item"><a class="w-100 btn btn-outline-secondary text-decoration-none " href="{% url url_upd item.pk %}">Изменить</a></li>
                <li class="list-group-item"><a class="w-100 btn btn-outline-danger text-decoration-none" href="{% url url_del item.pk %}">Удалить</a></li>
            {% endif %}
        </ul>
    </div>        
</div>

src/templates/header.html
{% load static %}
{% load book_filter_tags %}

<header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
            <img src="{% static 'logo/logo.png' %}" width="45" height="45" alt="logo">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'books:main' %}" class="nav-link px-3 link-dark">Главная</a></li>
            <li><a href="#" class="nav-link px-3 d-block link-dark text-decoration-none dropdown-toggle" id="dropdownDirs" data-bs-toggle="dropdown" aria-expanded="false">Справочники</a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownDirs">
                    <li><a class="dropdown-item" href="{% url 'dirs:authors' %}">Авторы</a></li>
                    <li><a class="dropdown-item" href="{% url 'dirs:genres' %}">Жанры</a></li>
                    <li><a class="dropdown-item" href="{% url 'dirs:series_list' %}">Серии</a></li>
                    <li><a class="dropdown-item" href="{% url 'dirs:phs' %}">Издательства</a></li>
                </ul>

            </li>
            {% if request.user|has_group:'manager' %}
                <li><a href="{% url 'books:books_manager' %}" class="nav-link px-2 link-dark">Книги</a></li>
                <li><a href="{% url 'orders:m_list' %}" class="nav-link px-2 link-dark">Cписок заказов</a></li>
            {% else %}
                <li><a href="{% url 'books:books' %}" class="nav-link px-2 link-dark">Книги</a></li>
            {% endif %}
            </ul>
            <span class="mx-auto" >USD:{% get_current_rate %}BYN</span>

            <form action="{% url 'search:find' %}" method="GET" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" name="search" class="form-control" 
                placeholder="{% if request.args.search %} request.args.search {% else %} Найти... {% endif %}" >
            </form>

            {% if user.is_anonymous %}

            <a class="btn btn-outline-primary" href="{% url 'users:login'%}">Войти</a>

            {% else %}

                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class=" user-name">{{  user }}</span>
                    </a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="{% url 'users:profile' request.user.profile.pk %}">Профиль</a></li>
                        <li><a class="dropdown-item" href="{% url 'carts:cart' %}">Корзина</a></li>
                        <li><a class="dropdown-item" href="{% url 'orders:list' %}">Заказы</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
</header>

src/templates/pagination.html
<div class="pagination justify-content-center">
    <span class="step-links">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item ">  
                    <a class="page-link" href="?page=1">1</a>
                </li>
                    
                <li class="page-item ">  
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
            {% endif %}

            <span class="current">
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                  </li>
            </span>

            {% if page_obj.has_next %}
                <li class="page-item ">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
                    
                <li class="page-item ">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                </li>
            {% endif %}
        </ul>
    </span>
</div>