src/books/urls.py
from django.urls import path
from . import views


app_name = 'books'

urlpatterns = [
    path('main/', views.BookListMainPageView.as_view(), name='main'),

    path('', views.BookListView.as_view(), name='books'),
    path('book-create/', views.BookCreateView.as_view(), name='create'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book'),
    path('book-upd/<int:pk>', views.BookUpdateView.as_view(), name='update'),
    path('book-del/<int:pk>', views.BookDelView.as_view(), name='del'),
    path('import-CSV', views.ImportCSVView.as_view(), name='import_CSV'),

    path('manager-list/', views.BookManagerListView.as_view(), name='books_manager'),
    
]

src/directories/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name = 'dirs'

urlpatterns = [
    path('', views.TemplateView.as_view(template_name='directories/index.html'), name='dir_lists'),
    
    path('authors', views.AuthorsList.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetail.as_view(), name='author'),
    path('author-upd/<int:pk>', views.AuthorUpdate.as_view(), name='author_upd'),
    path('author-del/<int:pk>', views.AuthorDel.as_view(), name='author_del'),
    path('author-create/', views.AuthorCreate.as_view(), name='author_create'),

    path('genres', views.GenresList.as_view(), name='genres'),
    path('genre/<int:pk>', views.GenreDetail.as_view(), name='genre'),
    path('genre-upd/<int:pk>', views.GenreUpdate.as_view(), name='genre_upd'),
    path('genre-del/<int:pk>', views.GenreDel.as_view(), name='genre_del'),
    path('genre-create/', views.GenreCreate.as_view(), name='genre_create'),
    
    path('publishing-houses', views.PhList.as_view(), name='phs'),
    path('publishing-house/<int:pk>', views.PhDetail.as_view(), name='ph'),
    path('publishing-house-upd/<int:pk>', views.PhUpdate.as_view(), name='ph_upd'),
    path('publishing-house-del/<int:pk>', views.PhDel.as_view(), name='ph_del'),
    path('publishing-house-create/', views.PhCreate.as_view(), name='ph_create'),
    
    path('series', views.SeriesList.as_view(), name='series_list'),
    path('series/<int:pk>', views.SeriesDetail.as_view(), name='series'),
    path('series-upd/<int:pk>', views.SeriesUpdate.as_view(), name='series_upd'),
    path('series-del/<int:pk>', views.SeriesDel.as_view(), name='series_del'),
    path('series-create/', views.SeriesCreate.as_view(), name='series_create'),
] 

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from proj import settings

from django.http import HttpResponseRedirect
from django.urls import reverse



def redirect_to_books(request):
    return HttpResponseRedirect(reverse('books:books'))


urlpatterns = [
    path('admin/', admin.site.urls),
    path('directories/', include('directories.urls', namespace='dirs')),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('search/', include('search.urls', namespace='search')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('', redirect_to_books, name='main'),

] 


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

src/books/models.py
from django.db import models
from comments.models import Comment
from directories import models as dirs_models
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation

# Create your models here.

def book_directory_path(instance, filename):
    return f'books/{instance.name}'


class Book(models.Model):
    
    BINDING = [
        ('T', 'твердый'),
        ('М', 'мягкий'),
        ('др', 'другой'),
    ]

    FORMAT = [
        ('св_кр', 'сверхкрупная (84×108/16; 70×90/8)'),
        ('кр', 'крупная (70×90/16; 75×90/16)'),
        ('ср', 'средняя (60×90/16; 84×108/32)'),
        ('мал', 'малая (70×90/32; 70×108/32)'),
        ('св_м', 'сверхмалая (60×90/32)'),
    ]

    name = models.CharField(verbose_name='Имя', max_length=60, )
    discription = models.TextField(verbose_name='Описание', blank=True, null=True,)
    picture = models.ImageField(verbose_name='Изображение', upload_to=book_directory_path, blank=True, default='books/book0')
    price = models.FloatField(verbose_name='цена (BYN)')
    authors = models.ManyToManyField(to=dirs_models.Author, related_name='books')          # Автор
    series = models.ForeignKey(to=dirs_models.Series, verbose_name='серия', related_name='books', blank=True, null=True, on_delete=models.PROTECT)  # Серии
    genre = models.ManyToManyField(to=dirs_models.Genre, verbose_name='жанры', related_name='books',)    # Жанр
    pyblishing_year = models.IntegerField(verbose_name='год издания', blank=True, null=True, )
    pages = models.IntegerField(verbose_name='страниц', blank=True, null=True, )
    binding = models.CharField(verbose_name='переплет', max_length=2, choices=BINDING, default='др')
    format = models.CharField(verbose_name='формат', max_length=5, choices=FORMAT, default='ср')
    ISBN = models.CharField(verbose_name='ISBN номер', max_length=17, blank=True, null=True,)
    weight = models.IntegerField(verbose_name='вес, (гр.)', blank=True, null=True,)
    age_restrictions = models.CharField(verbose_name='возрастные ограничения', max_length=3, default='нет')
    ph = models.ForeignKey(to=dirs_models.PublishingHouse, verbose_name='Издательство', blank=True, null=True, related_name='books', on_delete=models.PROTECT) # издательства
    in_stock = models.IntegerField(verbose_name='кол-во в наличии',  blank=True, null=True,)
    available = models.BooleanField(verbose_name='доступна для заказа', default=False)
    rating = models.FloatField(verbose_name='рейтинг', blank=True, null=True,)
    created = models.DateTimeField(verbose_name = "Дата внесения в каталог", auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(verbose_name = "Дата последнего редактирования в БД", auto_now=True, auto_now_add=False)
    


    def __str__(self) -> str: 
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse('books:book', args=[self.pk])   #  можно так  bookshop:author, args=[self.pk]
        
    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

src/books/forms.py
from django import forms
from .models import Book 


class BookForm(forms.ModelForm):
    class Meta:
        model = Book 
        fields = '__all__'


class ImportCSVForm(forms.Form):
    csv_file = forms.FileField(required=True)
    next = forms.CharField(required=True)
    

src/books/views.py
from django.shortcuts import render
from django.views.generic import UpdateView, ListView, DetailView, CreateView, DeleteView, FormView 
from django.urls import reverse_lazy
from . import models
from . import forms
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
import csv
from directories import models as dmodels


# Create your views here.

class BookListView(ListView):
    model = models.Book
    paginate_by = 16


class BookManagerListView(ListView, PermissionRequiredMixin):
    template_name = 'books/book_list_manager.html'
    model = models.Book
    login_url = '/users/login/'
    permission_required = ('books.add_book', 'books.update_book', 'books.delete_book' )
    paginate_by = 40

class BookCreateView(PermissionRequiredMixin, CreateView):
    model = models.Book
    form_class = forms.BookForm
    login_url = '/users/login/'
    permission_required = "books.add_book"

    def get_context_data(self, **kwargs):
        cnt = super().get_context_data(**kwargs)
        cnt.update({'title': 'Создать книгу'})
        return cnt


class BookDetailView(DetailView):
    model = models.Book


class BookUpdateView(UpdateView, PermissionRequiredMixin):
    model = models.Book
    form_class = forms.BookForm
    permission_required = 'books.update_book'

    def get_context_data(self, **kwargs):
        cnt = super().get_context_data(**kwargs)
        cnt.update({'title': 'Изменить книгу'})
        return cnt


class BookDelView(DeleteView, PermissionRequiredMixin):
    model = models.Book
    success_url = reverse_lazy('books:books_manager',)
    permission_required = 'books.delete_book'

class BookListMainPageView(ListView):
    template_name = 'books/main.html'
    model = models.Book
    paginate_by = 4

    def get_context_data(self, **kwargs):
        cnt = super().get_context_data(**kwargs)
        new_books = models.Book.objects.all().filter(available=True).order_by('-created')[:8]
        popular_books = models.Book.objects.all().filter(available=True).order_by('-rating')[:8]
        cnt.update({
            'new_books': new_books,
            'popular_books': popular_books,
            })
        return cnt
    

class ImportCSVView(FormView):
    form_class = forms.ImportCSVForm
    success_url = reverse_lazy('books:books_manager')

    def get_authors(self, authors:str):
        Author = dmodels.Author
        authors = authors.split(',')
        result = []
        for author in authors:
            object, created = Author.objects.get_or_create(
                name=author.strip(),
                defaults={'discription':f'Тут должно быть описание {author}'},
            )
            result.append(object)
        return result

    def get_series(self, series:str):
        Series = dmodels.Series
        series, created = Series.objects.get_or_create(
                name=series.strip(),
                defaults={},
            )
        return series
    
    def get_genre(self, genres:str):
        Genre = dmodels.Genre
        genres = genres.split(',')
        result = []
        for genre in genres:
            object, created = Genre.objects.get_or_create(
                name=genre.strip(),
                defaults={'discription':f'Тут должно быть описание {genre}'},
            )
            result.append(object)
        return result

    def get_ph(self, ph:str):
        Ph = dmodels.PublishingHouse
        ph, created = Ph.objects.get_or_create(
                name=ph.strip(),
                defaults={},
            )
        return ph

    def form_valid(self, form):
        # try:
        file = self.request.FILES['csv_file'] 
        decoded_file = file.read().decode('utf-8').splitlines()
        reader = csv.DictReader(decoded_file)
        for row in reader:
            name = row.get('name')
            discription = row.get('discription')
            price = float(row.get('price'))
            authors = row.get('authors')
            series = row.get('series')
            genre = row.get('genre')
            pyblishing_year = int(row.get('pyblishing_year'))
            pages = int(row.get('pages'))
            binding = row.get('binding')
            format = row.get('format')
            ISBN = row.get('ISBN')
            weight = int(row.get('weight'))
            age_restrictions = row.get('age_restrictions')
            ph = row.get('ph')
            in_stock = int(row.get('in_stock'))
            available = True if row.get('in_stock') == '+' else False
            rating = float(row.get('rating'))

            print(format, '**********************************************************')

            authors = self.get_authors(authors)
            if series:
                series = self.get_series(series)
            genre = self.get_genre(genre)
            ph = self.get_ph(ph)
            
            book = models.Book(name=name,
                discription=discription,
                    price=price,
                    series=series,
                    pyblishing_year=pyblishing_year,
                    pages=pages,
                    binding=binding,
                    format=format,
                    ISBN=ISBN,
                    weight=weight,
                    age_restrictions=age_restrictions,
                    ph=ph,
                    in_stock=in_stock,
                    available=available,
                    rating=rating,
            )
            book.save()
            auths = (a.pk for a in authors)
            book.authors.add(*auths)
            gs = (g.pk for g in genre)
            book.genre.add(*gs)
            book.save()

        # except BaseException:
        #     messages.add_message(self.request, messages.WARNING, f'{self.request.user}, Произошла ошибка при импорте СSV файла!')
        return super().form_valid(form)
        #  HttpResponseRedirect(reverse_lazy('books:books_manager'))




    

src/books/templates/books/book_confirm_delete.html
{% extends "base.html" %}
    
{% block title %}
    Удаление книги
{% endblock title %}    

{% block body %}
    <div class="col-8">
        <h1>Удалить книгу: {{ object.name }}?</h1>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class=" btn btn-outline-danger">Удалить</button>
            <a class=" btn btn-outline-secondary" href="{{ back_link }}">Отмена</a></p>
            
        </form>
    </div>
{% endblock body %}

src/books/templates/books/book_detail.html
{% extends "base.html" %}
{% load comments_tags %}

{% block title %}
    {{object.name}}
{% endblock title %}    

{% block body %}
    <div class="container-fluid">
    
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-5 col-lg-4">    
                <img class="rounded mx-auto d-block img-thumbnail img-fluid"  src="{{ object.picture.url }}" alt="book_pict">
                <hr>
                <a class="w-100 btn btn-success" href="#">Добавить в корзину</a>
            </div>        

            <div class="col-xs-12 col-sm-6 col-md-7 col-lg-8">
                <h2><b>name:</b> <em> {{ object.name }}({{object.pyblishing_year}}) </em>   </h2>
                <p><b>Описание:</b><br>    
                {{ object.discription }} <br>
                <b>Серия:</b> {{ object.series.name }} <br>                
                <b>Переплет: </b> {{ object.get_binding_display }} <br>
                <b>Количество страниц: </b> {{ object.pages }} <br>
                <b>Формат: </b> {{ object.get_format_display }} <br>
                <b>ISBN: </b> {{ object.ISBN }} <br>
                <b>Вес: </b> {{ object.weight }} (гр) <br>
                <b>Возрастные ограничения: </b> {{ object.age_restrictions }} <br>
                <b>Рейтинг: </b> {{ object.rating }} <br>

                </p>
            </div>
     
        </div>
        
        <div class="container">
            <b>Автор:</b> 
            {% for author in object.authors.all %}
                <a class="text-reset text-decoration-none link-hover" href="{% url 'dirs:author' author.pk %}"> {{author.name}} </a>
            {% endfor %}
            <span>  |  </span>
            <b>Жанр:</b> 
                {% for genre in object.genre.all %}
                <a class="text-reset text-decoration-none link-hover" href="{% url 'dirs:genre' genre.pk %}"> {{genre.name}} </a>
                {% endfor %}
            {% if object.ph %}        
                <span>  |  </span>
                <b>Издательство: </b> 
                <a class="text-reset text-decoration-none link-hover" href="{% url 'dirs:ph' object.ph.pk %}"> {{ object.ph }}</a> 
            {% endif %}    
        </div>

        <div>
            <p class="text-end text-down"> Последнее обновление: {{ object.updated|date:'d-m-y H:i:s' }}</p>
        </div>

        <div class="comments  col-lg-8 col-sm-12 ">
            {% show_comments %}
        </div>
    </div>
{% endblock body %}

src/books/templates/books/book_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{ title }}
{% endblock title %}
    
{% block body %}
    <div class="container col col-lg-8" >
        
        <div class="row">
            {% if object.picture %}    
                <div class="col-5">
                    <img class="img-thumbnail img-fluid" src="{{ object.picture.url }}" alt="book_pict">
                </div>
            {% endif %}    
            <div class="col-7">
                <h1>{{ title }}</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    {{ form|crispy  }}

                    <div class="form-actions">         
                    <hr class="my-4">
                    <button class="w-100 btn btn-outline-success btn-lg" type="submit">Подтвердить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

src/books/templates/books/book_list.html
{% extends "base.html" %}

{% block title %}
Books
{% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class="d-flex bd-highlight mb-3">
        <div class="p-2 bd-highlight fs-3">Книги:</div> 
        <div class="ms-auto p-2 bd-highlight"><a class=" btn btn-outline-success justify-content-end text-decoration-none" href="{% url 'books:create' %}">Добавить</a></div>
    </div>
    <hr>  
    <div class="row">
        {% for book in object_list %}
            {% include 'book_card.html' %}
        {% endfor %}
    </div>
    <br>

</div>

{% include 'pagination.html' %}




{% endblock body %}

src/books/templates/books/book_list_manager.html
{% extends "base.html" %}

{% block title %}
Books
{% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class=" mb-3">
        <div class="p-2  fs-3">Книги:</div> 
        <hr> 
        <div class="justify-content-end">
            <form action="{% url 'books:import_CSV' %}" method="post" enctype="multipart/form-data" class="row justify-content-end">
                {% csrf_token %}
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <input type="file" name="csv_file" class="form-control" id="customFile" accept=".csv, text/csv" />
                    <input type="hidden" name="next" value="{{ request.path }}"/>
                </div>
                <button class=" btn btn-outline-success col-lg-2 col-md-4 col-sm-12" style="display: inline;" type="submit">Загрузить CSV файл</button>
            </form>
        </div>
    </div>
    <hr>  
    <table class="table table-striped  ">
        <thead>
            <tr>
                <td class="text-center"><b>№</b></td>
                <td class="text-center"><b>Название</b></td>
                <td class="text-center"><b>Цена(BYN)</b></td>
                <td class="text-center"><b>В наличии</b></td>
                <td class="text-center"><b>Доступно для заказа</b></td>
                <td class="text-center"><b>Обновлено</b></td>
                <td class="text-center"><b><a class="w-50 btn btn-outline-success justify-content-end text-decoration-none" href="{% url 'books:create' %}">Добавить</a></b></td>
                
                
            </tr>
          </thead>
        <tbody>
            {% for item in object_list %}
                <tr>
                    <td class="text-center">{{forloop.counter}}</th>
                    <td class="text-center"><a class="text-decoration-none text-reset txt-overflow" href="{% url 'books:book' item.pk %}">{{ item.name }}</a></td>
                    <td class="text-center">{{ item.price }}</td>
                    <td class="text-center">{{ item.in_stock }}</td>
                    <td class="text-center">{{ item.available}}</td>
                    <td class="text-center">{{ item.updated }}</td>
                    <td class="text-end">
                        <a class=" btn btn-outline-secondary justify-content-end text-decoration-none " href="{% url 'books:update' item.pk %}">Изменить</a>
                        <a class=" btn btn-outline-danger justify-content-end text-decoration-none " href="{% url 'books:del' item.pk %}">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'pagination.html' %}




        
    </div>
    <br>

</div>
{% endblock body %}

src/books/templates/books/main.html
{% extends 'base.html' %} 
   
   
{% block title %}Список справочников{% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class="fs-2">
        Новые:
    </div>
    <hr>  
    <div class="row border border-3 rounded pb-4">
        {% for book in new_books %}
            {% include 'book_card.html' %}


        {% endfor %}
    </div>        
        <hr class="mt-4">  
    <div class="fs-2">
        Самые популярные:
    </div>
    <hr class="mt-2">  
    <div class="row border border-3 rounded pb-4">
        {% for book in popular_books %}
        {% include 'book_card.html' %}

        {% endfor %}
    </div>
    <br>





</div>    
{% endblock body %}

dictsortreversed