src/books/urls.py
from django.urls import path
from . import views


app_name = 'books'

urlpatterns = [
    path('main/', views.BookListMainPageView.as_view(), name='main'),

    path('', views.BookListView.as_view(), name='books'),
    path('book-create/', views.BookCreateView.as_view(), name='create'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book'),
    path('book-upd/<int:pk>', views.BookUpdateView.as_view(), name='update'),
    path('book-del/<int:pk>', views.BookDelView.as_view(), name='del'),
    path('import-CSV', views.ImportCSVView.as_view(), name='import_CSV'),

    path('manager-list/', views.BookManagerListView.as_view(), name='books_manager'),
    
]

src/carts/urls.py
from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('delete-book/<int:pk>', views.BookInCartDeleteView.as_view(), name='del_book'),
    path('update-cart', views.UpdateCartView.as_view(), name='upd_cart'),
]

src/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.CreateOrderView.as_view(), name='create'),
    path('list/', views.OrderListView.as_view(), name='list'),
    path('manager-list/', views.OrderManagerListView.as_view(), name='m_list'),
    path('update/<int:pk>', views.OrderManagerUpdateView.as_view(), name='update'),
    path('cancel/<int:pk>', views.CancelOrderView.as_view(), name='cancel'),
    path('comment/<int:pk>', views.CommentOrderView.as_view(), name='comment'),
] 

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from proj import settings

from django.http import HttpResponseRedirect
from django.urls import reverse



def redirect_to_books(request):
    return HttpResponseRedirect(reverse('books:books'))


urlpatterns = [
    path('admin/', admin.site.urls),
    path('directories/', include('directories.urls', namespace='dirs')),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('search/', include('search.urls', namespace='search')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('', redirect_to_books, name='main'),

] 


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

src/users/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name = 'users'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile'),
    path('update-profile/<int:pk>', views.UpdateProfileView.as_view(), name='update'),


]    
    

src/orders/models.py
from django.db import models
from django.db.models import deletion
from django.db.models.fields import CharField
from carts.models import Cart


class OrderStatus(models.Model):
    name = CharField(
        verbose_name='Название',
        max_length=128,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказов'





class Order(models.Model):   
    cart = models.OneToOneField(
        Cart,
        verbose_name='Заказ',
        on_delete=models.PROTECT,
        related_name='order',   
    )
    phone_number = models.IntegerField(
        verbose_name='Номер телефона',
    )
    created = models.DateTimeField(verbose_name = "Дата внесения в каталог", auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(verbose_name = "Дата последнего редактирования в БД", auto_now=True, auto_now_add=False)
    status= models.ForeignKey(
        OrderStatus,
        verbose_name='Статус',
        related_name='orders',
        on_delete=models.PROTECT,
    )
    information = models.TextField(verbose_name='Доп. информация', blank=True, null=True,) 

    
    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

src/orders/forms.py
from django import forms
from . import models
from django.core.validators import RegexValidator


class OrderForm(forms.Form):
    phone_number = forms.CharField(
        required=True,
        label='Номер телефона (хх)ххх-хх-хх',
        validators=(RegexValidator(r'^(29|33|25|44)[1-9][0-9]{6}$', 'Не верный номер телефона.'),),
    )
    information = forms.CharField(label='Информация', required=False, help_text='Не обязательное поле.')

class OrderManagerForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ('status', 'information')

src/orders/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http.response import HttpResponseRedirect
from django.views.generic.detail import DetailView
from .models import Order, OrderStatus
from django.views.generic import FormView, ListView, UpdateView, RedirectView, TemplateView
from .forms import OrderForm, OrderManagerForm
from carts.models import Cart
from django.urls.base import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

# Create your views here.
class CreateOrderView( FormView):
    
    form_class = OrderForm
    template_name = 'orders/order.html'
    success_url = reverse_lazy('orders:list')

    def get_initial(self):
        user = self.request.user
        if user.is_anonymous:
            return
        profile = user.profile
        pn = profile.phonenumber
        information = f'{profile.country},'
        if profile.city and profile.adress_1 and profile._code:
            information += f'г.{profile.city}, {profile.adress_1}, {profile.post_code}'
        return {'phone_number':pn, 'information':information}
     
    def form_valid(self, form):
        cart_id = self.request.session.get('cart_id')
        cart = Cart.objects.get(pk=cart_id)
        status = OrderStatus.objects.get(name='новый')
        phone_number = form.cleaned_data.get('phone_number')
        information = form.cleaned_data.get('information')
        order = Order.objects.create(
            cart=cart,
            phone_number=phone_number,
            status=status,
            information=information,
        )
        del self.request.session['cart_id']
        print('hello*****************************************************************')
        messages.add_message(self.request, messages.INFO, f'{self.request.user}, Ваш заказ принят!')
        return HttpResponseRedirect(self.get_success_url())
    
    def get_context_data(self, **kwargs):
        cnt = super().get_context_data(**kwargs)
        cart = Cart.objects.get(pk=int(self.request.session.get('cart_id')))
        cnt['object']=cart
        return cnt


class OrderListView(ListView):
    template_name = 'orders/order_list.html'
    model = Order

    def get_context_data(self, **kwargs):
        user = self.request.user
        carts = user.carts.all()
        orders = Order.objects.order_by('-created').filter(cart__in=carts)
        cnt = {'object_list':orders}
        return cnt
    

class OrderManagerListView(PermissionRequiredMixin, ListView):
    template_name = 'orders/manager/order_list.html'
    model = Order
    login_url = '/users/login/'
    permission_required = 'orders.change_order'

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-created')
        status = self.request.GET.get('status')
        if status:
            queryset = queryset.all().filter(status__pk = status)
        print(queryset)
        return queryset


class OrderManagerUpdateView(PermissionRequiredMixin, UpdateView):
    model = Order
    template_name = 'orders/manager/order_update.html'
    form_class = OrderManagerForm
    success_url = reverse_lazy('orders:m_list')
    permission_required = 'orders.change_order'

    def get_context_data(self, **kwargs):
        cnt = super().get_context_data(**kwargs)
        order_pk = self.kwargs['pk']
        cart = Order.objects.get(pk=order_pk).cart
        cnt['cart'] = cart
        return cnt
    

class CancelOrderView(RedirectView):    
    def post(self, request, *args, **kwargs):
        order_pk = kwargs.get('pk')
        order = Order.objects.get(pk=order_pk)
        order_status = OrderStatus.objects.get(name='отменен')
        order.status = order_status
        order.save()
        return HttpResponseRedirect(reverse_lazy('orders:list'))


class CommentOrderView(DetailView):
    template_name = 'orders/comment.html'
    model = Order

src/orders/templates/orders/manager/order_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Заказы
{% endblock title %}    

{% block body %}
    <div class="container-fluid col col-lg-8 col-md-10">
        <div>
            <a class="btn btn-outline-secondary btn-sm" href="{% url 'orders:m_list' %}">Все</a>
            <a class="btn btn-outline-secondary btn-sm" href="{% url 'orders:m_list' %}?status=1">Новый</a>
            <a class="btn btn-outline-secondary btn-sm" href="{% url 'orders:m_list' %}?status=2">В обработке</a>
            <a class="btn btn-outline-secondary btn-sm" href="{% url 'orders:m_list' %}?status=3">В пути</a>
            <a class="btn btn-outline-secondary btn-sm" href="{% url 'orders:m_list' %}?status=4">Доставлен</a>
            <a class="btn btn-outline-secondary btn-sm" href="{% url 'orders:m_list' %}?status=5">Оплачен</a>
            <a class="btn btn-outline-secondary btn-sm" href="{% url 'orders:m_list' %}?status=6">Отменен</a>
        </div>
        <hr>

        <table class="table table-striped">
            <tr>
                <td>
                    <b> ID </b> 
                </td>
                <td>
                    <b> Книга(и) </b>
                </td>
                <td>
                    <b> Цена заказа </b>
                </td>
                <td>
                    <b> Дата оформления </b>
                </td>
                <td>
                    <b> Статус: </b>
                </td>
                <td>
                    
                </td>
            </tr>
            {% for order in object_list %}
            
                <tr>
                    <td>
                        {{ order.pk }}
                    </td>
                    <td>
                        <ul>
                            {% for book in order.cart.books_in_cart.all %}
                                <li>
                                    {{forloop.counter}}. {{book.book.name}} - {{book.quantity}}шт.
                                </li>                                
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        {{ order.cart.cart_price }}
                    </td>
                    <td>
                        {{ order.created|date:'d-m-y H:i' }}
                    </td>
                    <td>
                        {{order.status}}
                    </td>
                    <td>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'orders:update' order.pk %}">Изменить</a>
                        <a class="btn-sm btn btn-outline-secondary" href="{% url 'orders:comment' order.pk %}">Комментарии</a>
                    </td>
                </tr>
            
            {% endfor %}
        </table>        
            
    </div>
{% endblock body %}

src/orders/templates/orders/manager/order_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Заказ id:{{ object.id }}
{% endblock title %}    

{% block body %}
    <div class="container-fluid col col-lg-8 col-md-10">
        <div class="cart">
        
            Заказ ID: {{ object.pk }}  Корзина ID: {{ cart.pk }} Покупатель <a href="{% url 'users:profile' cart.customer.profile.pk %}">{{ cart.customer }}</a>
            <form action="{% url 'carts:upd_cart' %}" method="POST">
                
                <table class="table table-striped  ">
                    <thead>
                        <tr>
                            <td class="text-center"><b>№</b></td>
                            <td class="text-center"><b>Книга</b></td>
                            <td class="text-center"><b>Обложка</b></td>
                            <td class="text-center"><b>Цена за шт.(BYN)</b></td>
                            <td class="text-center"><b>Количество</b></td>
                            <td class="text-center"><b>Цена всей позиции(BYN)</b></td>
                            <td class="text-center"><b>Для кнопок</b></td>
                        </tr>
                    </thead>
                    <tbody> 
                        <form action="#" method="POST"></form>
                        <input type="hidden" name="next" value="{{ object.pk }}">
                        <input type="hidden" name="cart_id" value="{{ cart.pk }}">

                        {% for book in cart.books_in_cart.all %}
                            <tr>
                                <td class="text-center">{{forloop.counter}}</th>
                                <td class="text-center"><a class="text-decoration-none text-reset txt-overflow" href="{% url 'books:book' book.book.pk %}">{{ book.book.name }}</a></td>
                                <td class="text-center"><img src="{{ book.book.picture.url }}" alt="{{ book.book.name }}" style="width: 130px; height: auto;"></td>
                                <td class="text-center">{{ book.unit_price }}</td>
                                <td class="text-center">
                                    <input type="number" min="1" step="1" class="form-control" name="quantity_{{book.pk}}" value="{{ book.quantity }}" style="width: 40%; margin: auto;">
                                </td>
                                <td class="text-center">{{ book.total_price }}</td>
                                <td class="text-end">
                                    <form action="{% url 'carts:del_book' book.pk %}" method="POST">{%csrf_token%} <button class="btn btn-outline-danger">Удалить</button>    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        
                        <tr style="border: 2px black solid">
                            <td colspan='5' class="text-end"><b>Общая стоимость:</b></td>
                            <td class="text-center"><b>{{ cart.cart_price }}</b></td>
                            {% csrf_token %}
                            <td class="text-end"><button class="btn btn-outline-secondary btn-sm " value="save" name="submit" type="submit">Сохранить</button></td>
                        </tr>
                    </tbody>
                    
                </table> 
            </form>
                    
    
        </div>

        <div class="order">    
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-outline-success mt-2">Подтвердить</button>
            </form>

            
        </div>
    </div>
{% endblock body %}